version: '3.8'

services:
  moodle:
    # La versión de aules a 2024/06 es 3.11.17+ (Build: 20231201) (se ve en los backup)
    # image: moodlehq/moodleapp:3.9.5
    # image: moodlehq/moodle-php-apache:8.0
    image: bitnami/moodle:latest
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/moodledata
      # - ./moodle/config.php:/var/www/html/config.php
    environment:
      - MOODLE_URL=http://localhost:8080
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle_password
      - MOODLE_ADMIN=admin
      - MOODLE_PASSWORD=admin_password
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle_password
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

volumes:
  moodledata:
  dbdata:
