services:

  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=my_password
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      # - MOODLE_USERNAME=admin
      # - MOODLE_PASSWORD=admin
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=my_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
